### ISSUE TITLE
Aggregate test results by political boundaries

### ISSUE THREAD

**Issue by JohnTigue** [codeforseattle/seanetmap#1]
In the prototype from M-Lab, the test results are clustered into hexes tiling the city.

There are requirements ([CityReq2](https://github.com/codeforseattle/seanetmap/wiki/Requirements-from-the-City-of-Seattle,-Annotated#cityreq2-data-is-summarized-by-census-tract) and [CityReq3.1](https://github.com/codeforseattle/seanetmap/wiki/Requirements-from-the-City-of-Seattle,-Annotated#cityreq31) call for Census block and/or Census track) to aggregate test results according to political boundaries. 

Another layer (not in the requirements) could be aggregated results by Seattle City Council District (which was actually the first political boundary the work was preformed on).

First step was (well, actually GeoJSON should have been first, but, hey) to get TopoJSON files for the council districts. Closest that we found were shapefiles. Converting them to TopoJSON turned out to be a bit of a hassle but it's done now. See my write up:

https://github.com/JohnTigue/nodeio/tree/master/data/generating-topojson

**Comment by JohnTigue** [comment]
I'll commit the TopoJSON files to this project Tuesday or Wednesday. I think I want to move some files around in the repo first. Need to noodle that for a wee bit.

**Comment by willscott** [comment]
Cool!

**Comment by YonasBerhe** [comment]
Noted Great, I'm working on using leaflet with Angular.js. I hope to see you both at the code for Seattle meetup tomorrow.

**Comment by JohnTigue** [comment]
I'm not going to make that, physically. Is there a IRC/chat/slack/smoke-signals way to join remotely?

**Comment by YonasBerhe** [comment]
Do you have a Skype account? I'm more than willing to keep you updated that way.

**Comment by ptressel** [comment]
John -- Yes, there is a #codeforseattle channel on freenode.

**Comment by JohnTigue** [comment]
Thanks both. I'll be on #codeforseattle during the meetup

**Comment by JohnTigue** [comment]
Another M-Lab data client project that Ritzo, M-Lab PM, pointed to for non hex shapes:  
http://hyperiontest.gr/

**Comment by JohnTigue** [comment]
See also #9

**Comment by JohnTigue** [comment]
The TopoJSON has landed:
https://github.com/codeforseattle/seanetmap/blob/master/static/geojson/seattle-districts.json

There is code coming from M-Lab, probably this week that has something to do with clustering by polygon. From a Ritzo-Tigue email:
>- M-Lab developers are adding support to the example map for binning
data by a polygon file
> 
>Excellent! Please point me at that and I will merge it with the TopoJSON
files I generated of the Seattle City Council Districts as per issue #1:
https://github.com/codeforseattle/seanetmap/issues/1

>This will also get moving early next week on our end. I'm cc'ing Nathan
Kinkade and Georgia Bullen on this, since they're leading the effort on
that here. Nathan may have started on this today, but I'm not certain.
At the very least we'll have it rolled in next week.


So, the above two together should make for seeing test results by Seattle City Council District.

**Comment by critzo** [comment]
@nkinkade @georgiamoon

**Comment by nkinkade** [comment]
I've already written the initial code to allow [bq2geojson](https://github.com/m-lab/bq2geojson) to accept arbitrary polygon files (in GeoJSON format) rather than using the default of creating hexagons.  I haven't committed the changes yet, but will do so today after cleaning it all up a little and then integrating the changes into the prototype front-end.

Another feature I intend to implement in bq2geoson is that the Node.js script will output TopoJSON instead of GeoJSON, which should reduce the file sizes by >50%, greatly helping the speed at which a browser can load the files (especially when animating the map).  It will then be converted back to GeoJSON on the client side using [leaflet-omnivoire](https://github.com/mapbox/leaflet-omnivore).  This is based on the assumption (perhaps false) that the processing cost of converting the file type client-side will be less than the network cost of a larger polygon file, in terms of UX.

**Comment by JohnTigue** [comment]
@critzo Just tried to add @nkinkade @georgiamoon. Seems I do not not have that privilege. 

@willscott I'm assigning this to you as a "sub-issue." When the folks are added kick this issue back to me, please.

**Comment by JohnTigue** [comment]
FYI, #25 seems to be becoming th bq2geojson hub issue.

**Comment by willscott** [comment]
Collaborators added

**Comment by JohnTigue** [comment]
Currently the test results are being aggregated by City Council District maps. Census tracks to come.

Moving forward this is being tracked as #40 CityReq3 (User views the broadband map), which states:
>Map shows an overlay of census tracts over the City, with each tract color-coded by the state of broadband experience in the tract as defined in the summary section.

**Comment by JohnTigue** [comment]
Also see #37 CityReq2 (Data is summarized by census tract)
