### ISSUE TITLE
Troubleshooting bq2geojson to seanetmap GEO JSON import 

### ISSUE THREAD

**Issue by YonasBerhe** [codeforseattle/seanetmap#62]
Having problems getting the Geo JSON from Bq2geojson to show up on Seanetmap. What I'm trying to do right now is making sure that Seanetmap file structure is correct when corresponding and delegating files from Bq2geojson. Another issue might be that some new dependencies might have to be added to our map.

For right now those are all of the issues I can think of. As for the rest of the attributes of Bq2geojson for the most part they have made it over to our map.

**Comment by JohnTigue** [comment]
This has actually been fixed. The statics/ dir was unmaintainable what will sub projects added in without any order. So, I rebooted into client/. Pull and run and you will see. Also check out my commit messages from the last 24 hours.

**Comment by YonasBerhe** [comment]
Dude your awesome, well done!

**Comment by JohnTigue** [comment]
Thanks.
