### ISSUE TITLE
Aggregate test results by US Census boundaries

### ISSUE THREAD

**Issue by willscott** [codeforseattle/seanetmap#9]
A finer line than district that would be worth aggregating to would be census tract data.

**Comment by JohnTigue** [comment]
see also #1

**Comment by JohnTigue** [comment]
Census track maps are called for in [CityReq2](https://github.com/codeforseattle/seanetmap/wiki/Requirements-from-the-City-of-Seattle,-Annotated#cityreq2-data-is-summarized-by-census-tract) and [CityReq3.1](https://github.com/codeforseattle/seanetmap/wiki/Requirements-from-the-City-of-Seattle,-Annotated#cityreq31). We need to acquire such maps.

**Comment by JohnTigue** [comment]
Maps;
http://www.seattle.gov/dpd/cityplanning/populationdemographics/geographicfilesmaps/2010census/default.htm

ArcGIS Shapefiles
2010 Census geographic files derived from Census 2010 TIGER/Line files, projected to the City of Seattle standard projection and coordinate system.

King County Tracts (ZIP file)
King County Block Groups (ZIP file)
King County Blocks (ZIP file)

**Comment by JohnTigue** [comment]
Looking like the City wants census block as the level of aggregation

**Comment by JohnTigue** [comment]
This is being track as #37 and #40
